version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: company_info_app_prod
    environment:
      DB_TYPE: ${DB_TYPE:-postgres}
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      GOOGLE_PLACES_API_KEY: ${GOOGLE_PLACES_API_KEY}
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  postgres_data_prod:

